apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: broker-amq-pvol-broker-amq-0
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
        storage: 500Mi
 storageClassName: glusterfs-storage